name: PeeVeeEeeArena
main: no.runsafe.peeveeeeearena.PeeVeeEeeArena
version: 1.0.@BUILD@
author: Centralan
depend: [RunsafeMailbox, RunsafeWorldGuardBridge]
description:
commands:
  pvp:
    description: PvE related commands
